services:
  freeradius-core:
    build:
      context: .
      dockerfile: ./build-core/Dockerfile
    pull_policy: always
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /media/
        read_only: true
      - type: bind
        source: ./log/custom/
        target: /var/log/custom/
        read_only: false
      - type: bind
        source: ./log/freeradius/
        target: /var/log/freeradius
        read_only: false
    ports:
      - "1812-1813:1812-1813/udp"
    logging:
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"
